services:

  db:
    image: postgres:16
    container_name: fullstack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresDB:/var/lib/postgresql/data

volumes:
  postgresDB: